# Default values for kxi-rt.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 3

# Default image repository and pull settings for Insights Gateway chart components
image:
  repository: portal.dl.kx.com
  # component: kxi-rt
  pullPolicy: IfNotPresent

# This is for the secrets for pulling an image from a private repository.
# More information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets: []

#Â Can provide any valid q runtime argument here. Full details https://code.kx.com/q/basics/cmdline/
args: []

# Default common environment variables for the Resource Coordinator
# Additional ENVs can be added and these overridden in custom values files
# For Archiver configuration see - https://code.kx.com/insights/enterprise/configuration/rt-archival.html#raft-log-retention
envs:
  - name: RT_LOGLEVEL_CONSOLE
    value: "INFO"
  - name: RT_QURAFT_LOG_LEVEL
    value: "INFO"
  - name: RT_LOG_LEADER
    value: "1"

# This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
service:
  # This sets the service type more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
  type: ClusterIP
  # This sets the service annotations for the Internal RT Service. 
  # For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
  annotations: {}

# This is for setting up a additional external services
# Setting type to LoadBalancer and enabling will expose endpoints external to cluster.
# more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
externalService:
  # By default external services are disabled
  enabled: false
  # Set to true if you plan to add certification and utilize TCP for data publication
  useSsl: false
  # This sets the service type more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
  type: LoadBalancer
  # This sets the service annotations for the External RT Service. 
  # For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
  annotations: {}
  # This allows you to specify your LoadBalancer's external IP address
  # Should specify one per replica. e.g. 'replicaCount: 3', three IPs should be listed.
  # For more information checkout: https://kubernetes.io/docs/concepts/services-networking/service/#loadbalancer
  loadBalancerIPs: {}

# You must set your license name. Default is 'kc.lic'
# Available types are:
#  - kc.lic
#  - k4.lic
#  - kx.lic
kxLicenseName: kc.lic

persistence:
  # Capacity of claim.
  #
  capacity: 2Gi 
  # Unset means we use the default storage class. When using NFS, set this to
  # the configured storage class.
  #
  storageClass: ""
  accessModes:
  - ReadWriteOnce

raft:
  chunkSize: 0.25
  logSize: 2
  internalTimer: 10
  heartbeat: 1000

# This section builds out the service account more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# This is for setting Kubernetes Annotations to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
podAnnotations: {}

# This is for setting Kubernetes Labels to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
podLabels: {}

# Default pod security context for Reliable Transport chart components
podSecurityContext: 
  # 'nobody' user
  fsGroup: 65534
  runAsUser: 65534
  runAsNonRoot: true

# Default security context for Reliable Transport chart components
securityContext:
  readOnlyRootFilesystem: false
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # requests:
  #   memory: "1Gi"
  #   cpu: "1000m"
  # limits:
  #   memory: "1Gi"
  #   cpu: "1000m"

# This is to setup the liveness and readiness probes more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
livenessProbe:
  httpGet:
    path: /readiness
    port: 6000
  periodSeconds: 10
  successThreshold: 1
  initialDelaySeconds: 60
readinessProbe:
  httpGet:
    path: /readiness
    port: 6000
  periodSeconds: 2
  successThreshold: 2
  timeoutSeconds: 5

# Additional volumes on the output Deployment definition.
volumes: []

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []

# Allows adding node selector constraints to the Reliable Transport.
# For more information checkout: https://kubernetes.io/docs/tasks/configure-pod-container/assign-pods-nodes/
nodeSelector: {}

# Allows adding tolerations to the Reliable Transport.
# For more information checkout: https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/
tolerations: []


# Allows adding affinities to the Reliable Transport.
# For more information checkout: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity
affinity: {}

# Default Sidecar configuration for Reliable Transport chart components
kxiSidecar:
  # This sets overriding container image information. Use if you wish to target specific versions of the sidecar.
  # More information can be found here: https://kubernetes.io/docs/concepts/containers/images/
  image:
    tag: "1.16.0"

# Define how pods are created/deleted
# OrderedReady, sequential; Parallel, all at once
# More information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#pod-management-policies
podManagementPolicy: Parallel

# Define how pod updates are applied
# RollingUpdate, replace gradually; OnDelete, replace only on delete
# More information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#update-strategies
updateStrategy: {}
