---
networks:
  kx:
    name: kx
    driver: bridge

services:
  prometheus:
    hostname: promstats
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus-config.yml:/etc/prometheus/prometheus.yml
    networks: [kx]
  grafana:
    image: grafana/grafana-oss
    ports:
      - 3000:3000
    networks: [kx]
    environment:
      # - GF_SECURITY_ADMIN_USER=admin
      # - GF_SECURITY_ADMIN_PASSWORD=grafana
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/var/lib/grafana/dashboards/ingest.json
    volumes:
      - ./grafana-cfg/grafana/provisioning:/etc/grafana/provisioning
      - ./grafana-cfg/grafana/dashboards:/var/lib/grafana/dashboards
