apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "kxi-gw.sg.labels" . | nindent 4 }}
    app: {{ include "kxi-gw.fullname" . }}-sg
  name: {{ include "kxi-gw.fullname" . }}-sg
spec:
  replicas: {{ .Values.kxiSg.replicaCount }}
  selector:
    matchLabels:
      {{- include "kxi-gw.sg.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.kxiSg.podAnnotations }}
      annotations:
        {{- tpl ( toYaml . ) $ | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kxi-gw.sg.labels" . | nindent 8 }}
        {{- with .Values.kxiSg.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        app: {{ include "kxi-gw.fullname" . }}-sg
    spec:
      serviceAccountName: {{ include "kxi-gw.fullname" . }}-sg
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: sg
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}/kxi-sg-gw:{{ .Values.kxiSg.image.tag | default .Chart.AppVersion }}"
          ports:
            - containerPort: {{ .Values.kxiSg.service.ports.qipc }}
              protocol: TCP
            - containerPort: {{ .Values.kxiSg.service.ports.http }}
              protocol: TCP
            - containerPort: 8081
              protocol: TCP
          env:
            - name: GATEWAY_HTTP_PORT
              value: {{ .Values.kxiSg.service.ports.http | quote }}
            - name: GATEWAY_QIPC_PORT
              value: {{ .Values.kxiSg.service.ports.qipc | quote }}
            - name: KXI_SG_METRICS_ENABLED
              value: "true"
            - name: KXI_SG_METRICS_PORT
              value: "8081"
            - name: KXI_SG_RC_ADDR
              value: {{ include "kxi-gw.fullname" . }}-rc:{{ .Values.kxiRc.service.port }}
            - name: USE_SP_WATCHER
              value: "1"
            {{- if .Values.kxiSg.customIpcAuth.enabled }}
            - name: GATEWAY_EXT_QIPC_PORT
              value: {{ .Values.kxiSg.service.ports.qipcext | quote }}
            - name: KXI_SG_AUTH_IPC_HOST
              value: "localhost"
            - name: KXI_SG_AUTH_IPC_PORT
              value: {{ .Values.kxiSg.customIpcAuth.sidecar.port | quote }}
            - name: KXI_SG_AUTH_IPC_USE_TLS
              value: {{ .Values.kxiSg.customIpcAuth.sidecar.useTls | quote }}
            - name: KXI_SG_AUTH_IPC_AUTH_API
              value: {{ .Values.kxiSg.customIpcAuth.sidecar.authApi | quote }}
            {{- end }}
            {{- with .Values.kxiSg.envs }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          volumeMounts:
            - name: tmp
              mountPath: "/tmp"
              readOnly: false
            {{- with .Values.kxiSg.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
        {{- if .Values.kxiSg.customIpcAuth.enabled }}
        - name: auth-provider
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.kxiSg.customIpcAuth.sidecar.image.repository }}/{{ .Values.kxiSg.customIpcAuth.sidecar.image.name }}:{{ .Values.kxiSg.customIpcAuth.sidecar.image.tag }}"
          imagePullPolicy: {{ .Values.kxiSg.customIpcAuth.sidecar.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.kxiSg.customIpcAuth.sidecar.port }}
              protocol: TCP
          env:
            {{- with .Values.kxiSg.customIpcAuth.sidecar.envs }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          volumeMounts:
            - name: insights-kx-license
              mountPath: /opt/kx/lic
              readOnly: true
            {{- with .Values.kxiSg.customIpcAuth.sidecar.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.kxiSg.customIpcAuth.sidecar.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- end }}
      restartPolicy: Always
      volumes:
        - name: tmp
          emptyDir:
            sizeLimit: 100Mi
        {{- with .Values.kxiSg.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if .Values.kxiSg.customIpcAuth.enabled }}
        - name: insights-kx-license
          secret:
            defaultMode: 420
            items:
              - key: license
                path: {{ .Values.kxLicenseName }}
            optional: false
            secretName: kx-license
        {{- with .Values.kxiSg.customIpcAuth.sidecar.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- end }}
      {{- with .Values.kxiSg.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.kxiSg.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.kxiSg.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}