apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kxi-gw.fullname" . }}-rc
  labels:
    {{- include "kxi-gw.rc.labels" . | nindent 4 }}
    app: {{ include "kxi-gw.fullname" . }}-rc
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "kxi-gw.rc.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        checksum/log: {{ include ( print $.Template.BasePath "/qlogconfigmap.yaml" ) . | sha256sum }}
        checksum/config: {{ include ( print $.Template.BasePath "/kxi-rc-sidecarconfigmap.yaml" ) . | sha256sum }}
        {{- with .Values.kxiRc.podAnnotations }}
        {{- tpl ( toYaml . ) $ | nindent 8 }}
        {{- end }}
      labels:
        {{- include "kxi-gw.rc.labels" . | nindent 8 }}
        {{- with .Values.kxiRc.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        app: {{ include "kxi-gw.fullname" . }}-rc
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: rc
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}/kxi-sg-rc:{{ .Values.kxiRc.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.kxiRc.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.kxiRc.args }}
          args: 
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - containerPort: {{ .Values.kxiRc.service.port }}
              protocol: TCP
          env:
            - name: KXI_CONFIG_FILE
              value: "/opt/kx/sidecarConfig/config.json"
            - name: KXI_NAME
              value: {{ include "kxi-gw.fullname" . }}-rc
            - name: KXI_PORT
              value: {{ .Values.kxiRc.service.port | quote }}
            - name: KXI_ALLOWED_SBX_APIS
              value: {{ .Values.kxiRc.allowedSbxApis | quote }}
            - name: KXI_LOG_CONFIG
              value: /opt/kx/config/qlog.json
            {{- with .Values.kxiRc.envs }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          volumeMounts:
            {{- with .Values.kxiRc.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            - name: tmp
              mountPath: "/tmp"
              readOnly: false
            - name: {{ include "kxi-gw.fullname" . }}-rc-sidecar
              mountPath: /opt/kx/sidecarConfig/
            - name: {{ include "kxi-gw.fullname" . }}-log
              mountPath: /opt/kx/config
            - name: insights-kx-license
              mountPath: /opt/kx/lic
              readOnly: true
        - name: sidecar
          image: "{{ .Values.image.repository }}/kxi-sidecar:{{ .Values.kxiSidecar.image.tag | default .Chart.AppVersion }}"
          args: ["-p", "8080" ]
          ports:
            - containerPort: 8080
              name: metrics
          env:
            - name: KXI_CONFIG_FILE
              value: "/opt/kx/sidecarConfig/config.json"
            - name: KXI_LOG_CONFIG
              value: /opt/kx/config/qlog.json
          volumeMounts:
            - name: tmp-sidecar
              mountPath: "/tmp"
              readOnly: false
            - name: {{ include "kxi-gw.fullname" . }}-rc-sidecar
              mountPath: /opt/kx/sidecarConfig/
            - name: {{ include "kxi-gw.fullname" . }}-log
              mountPath: /opt/kx/config
            - name: insights-kx-license
              mountPath: /opt/kx/lic
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: tmp
          emptyDir:
            sizeLimit: 100Mi
        - name: tmp-sidecar
          emptyDir:
            sizeLimit: 100Mi
        - name: insights-kx-license
          secret:
            defaultMode: 420
            items:
              - key: license
                path: {{ .Values.kxLicenseName }}
            optional: false
            secretName: kx-license
        {{- with .Values.kxiAgg.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        - name: {{ include "kxi-gw.fullname" . }}-rc-sidecar
          configMap:
            name: {{ include "kxi-gw.fullname" . }}-rc-sidecar
        - name: {{ include "kxi-gw.fullname" . }}-log
          configMap:
            name: {{ include "kxi-gw.fullname" . }}-log

      {{- with .Values.kxiRc.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.kxiRc.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.kxiRc.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}