
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kxi-db.fullname" . }}-dalog
  labels:
    {{- include "kxi-db.da.labels" . | nindent 4 }}
data:
  qlog.json: |-
    {
      "endpoints": [
        "fd://stdout"
      ],
      "formatMode": "json",
      "routings": {
        "DEFAULT": "INFO"
      }
    }