apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kxi-db.fullname" . }}-da-sidecar
  labels:
    {{- include "kxi-db.da.labels" . | nindent 4 }}
data:
  config.json: |-
      {
        "connection": "::{{ .Values.kxiDa.service.port }}",
        "frequencySecs": 5,
        "metrics": {
          "enabled": "true",
          "frequency": 5,
          "handler": {
            "pc": true,
            "pg": true,
            "ph": true,
            "po": true,
            "pp": true,
            "ps": true,
            "ts": true,
            "wc": true,
            "wo": true,
            "ws": true
          }
        }
      }