apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kxi-sp.fullname" . }}-config
  labels:
    {{- include "kxi-sp.labels" . | nindent 4 }}
data:
  # Empty so that it doesn't overwrite logging config. Value is modified when a call is made to the
  # `/log` api
  loglevel.txt: |